FROM node:24-alpine


WORKDIR /app

# root権限で実行
USER root
RUN apk add --no-cache shadow ca-certificates

# ルートCAをOSのストアに追加
COPY rootCA.pem /usr/local/share/ca-certificates/rootCA.crt
RUN update-ca-certificates

ARG UID=1000
ARG GID=1000

RUN groupmod -g "${GID}" node && \
    usermod -u "${UID}" -g "${GID}" node

RUN chown -R node:node /app

USER node

# 依存関係を先にコピー（キャッシュ効率化）
COPY --chown=node:node package*.json ./
RUN npm ci

# 全ソースコードをコピー
COPY --chown=node:node . .

# Next.js 開発サーバーのポート(書かなくても動く)
EXPOSE 3000

# 開発モードで起動
CMD ["npm", "run", "dev"]
