FROM node:24-alpine

WORKDIR /app

ARG UID=1000
ARG GID=1000

RUN apk add --no-cache shadow

RUN groupmod -g "${GID}" node && \
    usermod -u "${UID}" -g "${GID}" node

RUN chown -R node:node /app

USER node

COPY --chown=node:node package*.json ./
RUN npm ci

COPY --chown=node:node . .

# Next.js 開発サーバーのポート(書かなくても動く)
EXPOSE 3000

# 開発モードで起動
CMD ["npm", "run", "dev"]
